# Site Settings
title: All Hands Active
subtitle: Ann Arbor's Maker Space!
author:
  name: All Hands Active
  email: board@allhandsactive.org
description: >- 
  Ann Arbor's Maker Space! Offering tools, resources, classes,
  meet-ups, events, and workspace for makers and hackers in the
  A2 and Ypsi area.
baseurl: ''
url: 'https://site2.allhandsactive.org'
repository: 'allhandsactive/site'


# Social media variables
twitter_username: AllHandsActive
facebook_username: AHA-All-Hands-Active-300100514925
meetup_username: allhandsactive
github_username:  allhandsactive


# Build settings
kramdown:
  input: GFM
exclude: ['Gemfile', 'Gemfile.lock', 'README.md', 'LICENSE']
include: ["_pages"]
permalink: pretty


# Theme settings
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: 'air'
title_separator: '|'
teaser: /assets/images/electronics-repair.jpg # fallback teaser, overridden in page yaml
logo: /assets/images/logo.png


# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap