title: All Hands Active
email: board@allhandsactive.org
description: >- # this means to ignore newlines until "baseurl:"
  Ann Arbor's Maker Space! Offering tools, resources, classes,
  meet-ups, events, and workspace for makers and hackers in the
  A2 and Ypsi area.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://site2.allhandsactive.org" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: AllHandsActive
github_username:  allhandsactive

# change social media variables to fit theme
facebook_username: AHA-All-Hands-Active-300100514925
meetup_username: allhandsactive

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
